### ISSUE TITLE
Publish a new version for `focus-visible` renaming

### ISSUE THREAD

**Issue by ryuran** [jonathantneal/postcss-focus-ring#3]
Hello @jonathantneal 

The is only version for focus visible published on npm https://www.npmjs.com/package/postcss-focus-ring.

This package should match to https://www.npmjs.com/package/focus-visible

**Comment by jonathantneal** [comment]
Resolved via https://github.com/jonathantneal/postcss-focus-visible/commit/42b81e478a9f3b279f813e901b0992a7c3a92d91

Thanks!
